---

{{- if .Values.slack_registration.ingress.enabled -}}
{{- $fullName := include "slack-registration.fullname" . -}}
{{- $servicePort := .Values.slack_registration.services.nginx.httpPort.servicePort -}}
{{- $ingressPath := .Values.slack_registration.ingress.path -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "slack-registration.name" . }}
    chart: {{ template "slack-registration.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.slack_registration.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ingressClassName: nginx
{{- if .Values.slack_registration.ingress.tls }}
  tls:
  {{- range .Values.slack_registration.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.slack_registration.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
  {{- end }}
{{- end }}
