---
global:
  registry: ""

slack_registration:
  images:
    nginx:
      repository: docker.io/nginx
      tag: 1.23-alpine
      pullPolicy: IfNotPresent

  nginx_config: |
    server {
      listen 80;
      listen [::]:80;
      server_name slack.developers.italia.it;

      location /badge.svg {
        return 301 https://img.shields.io/badge/slack-get%20invite-blue.svg?logo=slack;
      }

      location / {
        return 302 https://join.slack.com/t/developersitalia/shared_invite/zt-1nq6yyw6d-uAivR7ITcQFNOHZcMxKqvw;
      }
    }

  services:
    nginx:
      httpPort:
        servicePort: 80
        containerPort: 80

  ingress:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      cert-manager.io/acme-challenge-type: http01
    path: /
    hosts:
      - slack.developers.italia.it
    tls:
      - hosts:
          - slack.developers.italia.it
        secretName: slack-developers-italia-it-prod-tls

  resources:
    # For each of the following objects, set limits
    # removing the curly brackets after resources and
    # uncommenting the lines below.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
    nginx: {}

  nodeSelector: {}

  tolerations: {}

  affinity: {}
