---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "crawler.fullname" . }}
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  schedule: "{{ .Values.crawler.cronjob_schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: "{{ template "crawler.fullname" . }}"
        spec:
          securityContext:
            fsGroup: 1000

          containers:
          - name: {{ template "crawler.fullname" . }}
            image: "{{ .Values.global.registry }}{{ .Values.crawler.images.crawler.repository }}:{{ tpl .Values.crawler.images.crawler.tag . }}"
            imagePullPolicy: {{ .Values.crawler.images.crawler.pullPolicy }}

            command: ["./start.sh"]

            volumeMounts:
            - name: configs
              mountPath: /go/developers-italia-backend/crawler/domains.yml
              subPath: domains.yml
              readOnly: true
            - name: data
              mountPath: /var/crawler/data
              readOnly: false
            - name: output
              mountPath: /var/crawler/output
              readOnly: false

            resources:
{{ toYaml .Values.crawler.resources.crawler | indent 14 }}
            env:
              - name: ELASTIC_URL
                value: "{{ .Values.crawler.env.elastic_url }}"
              - name: ELASTIC_USER
                value: "{{ .Values.crawler.env.elastic_user }}"
              - name: ELASTIC_PWD
                value: crawler-secrets@azurekeyvault?elastic-pass

          restartPolicy: Never

          volumes:
          - name: configs
            secret:
              secretName: {{ template "crawler.fullname" . }}-secrets
              items:
              - key: domains.yml
                path: domains.yml
          - name: data
            persistentVolumeClaim:
              claimName: crawler-data
          - name: output
            persistentVolumeClaim:
              claimName: crawler-output
