---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "crawler.fullname" . }}
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "{{ .Values.crawler.cronjob_schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: "{{ template "crawler.fullname" . }}"
        spec:
          containers:
          - name: {{ template "crawler.fullname" . }}
            image: "{{ .Values.global.registry }}{{ .Values.crawler.images.repository }}:{{ tpl .Values.crawler.images.tag . }}"
            imagePullPolicy: {{ .Values.crawler.images.pullPolicy }}

            command: ["./wait-for-it.sh"]
            args: ["$(ELASTIC_HOST)", "-t", "300", "--", "./start.sh"]

            resources:
{{ toYaml .Values.crawler.resources | indent 14 }}
            env:
              - name: ELASTIC_HOST
                value: "{{ .Values.crawler.env.elastic_host }}"
              - name: ELASTIC_USER
                value: "{{ .Values.crawler.env.elastic_user }}"
              - name: ELASTIC_PASS
                value: crawler-secrets@azurekeyvault?elastic-pass

          restartPolicy: OnFailure
