---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ template "crawler.fullname" . }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-secret-store
  target:
    name: {{ template "crawler.fullname" . }}-azure-kv
  dataFrom:
    - extract:
        key: k8s-secrets-{{ template "crawler.fullname" . }}
