apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ template "crawler.fullname" . }}
spec:
  provider: azure
  parameters:
    keyvaultName: devita-prod-kv # The name of the Azure Key Vault
    useVMManagedIdentity: "true"
    userAssignedIdentityID: d7174ca3-5901-47ce-a1f6-32ec772f0de5
    objects: |
      array:
        - |
          objectName: k8s-secrets-elasticsearch-password
          objectType: secret
        - |
          objectName: k8s-secrets-crawler-domains-yml
          objectType: secret
    tenantId: f7f7d6c7-92de-488e-b37e-8963207c7b86
  secretObjects:
    - data:
        - key: elastic-pass # data field to populate
          objectName: k8s-secrets-elasticsearch-password
        - key: domains.yml
          objectName: k8s-secrets-crawler-domains-yml
      secretName: {{ template "crawler.fullname" . }}-azure-kv # name of the Kubernetes Secret object
      type: Opaque
