apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kibana
spec:
  provider: azure
  parameters:
    keyvaultName: devita-prod-kv
    useVMManagedIdentity: "true"
    userAssignedIdentityID: d7174ca3-5901-47ce-a1f6-32ec772f0de5
    objects: |
      array:
        - |
          objectName: k8s-secrets-elasticsearch-password
          objectType: secret
    tenantId: f7f7d6c7-92de-488e-b37e-8963207c7b86
  secretObjects:
    - data:
        - key: elasticsearch-password
          objectName: k8s-secrets-elasticsearch-password
      secretName: kibana-azure-kv
      type: Opaque
