global:
  resolve_timeout: 5m
route:
  group_by:
    - job
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: "null"
  routes:
    - match:
        alertname: Watchdog
      receiver: "null"
    - match:
        alertname: KubeCPUOvercommit
        prometheus: monitoring/prometheus-prometheus-oper-prometheus
        severity: warning
      receiver: "null"
    - match:
        alertname: KubeMemOvercommit
        prometheus: monitoring/prometheus-prometheus-oper-prometheus
        severity: warning
      receiver: "null"
    - match:
        alertname: NodeClockSkewDetected
      receiver: "null"
    - match:
        alertname: InfoInhibitor
        severity: none
      receiver: "null"
    - match_re:
        severity: ^(none|warning|critical)$
      receiver: SlackPrjSwat
receivers:
  - name: "null"
  - name: SlackPrjSwat
    slack_configs:
      - api_url: YOUR_SLACK_WEBHOOK_URL
        channel: YOUR_SLACK_CHANNEL
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Prometheus Event Notification'
        title_link: '{{ template "slack.default.titlelink" . }}'
        pretext: "{{ .CommonAnnotations.summary }}"
        text: |-
          {{ range .Alerts }}
            {{- if .Annotations.summary }}*Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`{{- end }}
            *Description:* {{ .Annotations.description }}{{ .Annotations.message }}
            *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:>{{ if or .Annotations.runbook .Annotations.runbook_url }} *Runbook:* <{{ .Annotations.runbook }}{{ .Annotations.runbook_url }}|:spiral_note_pad:>{{ end }}
            *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
