apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-kv-secret-store
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      # clientId of azureKeyvaultSecretsProvider
      identityId: d7174ca3-5901-47ce-a1f6-32ec772f0de5
      vaultUrl: https://devita-prod-kv.vault.azure.net
