apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-kv-secret-store
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      vaultUrl: https://devita-prod-kv.vault.azure.net
