apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ template "onboarding.fullname" . }}
spec:
  provider: azure
  parameters:
    keyvaultName: devita-prod-kv
    useVMManagedIdentity: "true"
    userAssignedIdentityID: d7174ca3-5901-47ce-a1f6-32ec772f0de5
    objects: |
      array:
        - |
          objectName: k8s-secrets-{{ template "onboarding.fullname" . }}-smtp-password
          objectType: secret
        - |
          objectName: k8s-secrets-{{ template "onboarding.fullname" . }}-paseto-key
          objectType: secret
    tenantId: f7f7d6c7-92de-488e-b37e-8963207c7b86
  secretObjects:
    - data:
        - key: smtp-password
          objectName: k8s-secrets-{{ template "onboarding.fullname" . }}-smtp-password
        - key: paseto-key
          objectName: k8s-secrets-{{ template "onboarding.fullname" . }}-paseto-key
      secretName: {{ template "onboarding.fullname" . }}-azure-kv
      type: Opaque
