apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: onboarding-staging
spec:
  provider: azure
  parameters:
    keyvaultName: devita-prod-kv
    useVMManagedIdentity: "true"
    userAssignedIdentityID: d7174ca3-5901-47ce-a1f6-32ec772f0de5
    objects: |
      array:
        - |
          objectName: k8s-secrets-onboarding-smtp-password
          objectType: secret
        - |
          objectName: k8s-secrets-onboarding-staging-paseto-api-token
          objectType: secret
    tenantId: f7f7d6c7-92de-488e-b37e-8963207c7b86
  secretObjects:
    - data:
        - key: smtp-password
          objectName: k8s-secrets-onboarding-smtp-password
        - key: paseto-key
          objectName: k8s-secrets-onboarding-staging-paseto-api-token
      secretName: onboarding-staging-azure-kv
      type: Opaque
