---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: elasticsearch
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-secret-store
  target:
    name: elasticsearch-azure-kv
  dataFrom:
    - extract:
        key: k8s-secrets-elasticsearch

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: elasticsearch-certs
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-secret-store
  target:
    name: elasticsearch-certs-azure-kv
    template:
      type: kubernetes.io/tls
      engineVersion: v2
      data:
        tls.crt: "{{ .crt | b64dec }}"
        tls.key: "{{ .key | b64dec }}"
  data:
    - secretKey: crt
      remoteRef:
        key: k8s-secrets-elasticsearch-certs-pem-02
        property: crt
    - secretKey: key
      remoteRef:
        key: k8s-secrets-elasticsearch-certs-pem-02
        property: key
