apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: publiccode-crawler-with-api
spec:
  provider: azure
  parameters:
    keyvaultName: devita-prod-kv # The name of the Azure Key Vault
    useVMManagedIdentity: "true"
    userAssignedIdentityID: d7174ca3-5901-47ce-a1f6-32ec772f0de5
    objects: |
      array:
        - |
          objectName: k8s-secrets-publiccode-crawler-api-bearer-token
          objectType: secret
        - |
          objectName: k8s-secrets-publiccode-crawler-github-token
          objectType: secret
    tenantId: f7f7d6c7-92de-488e-b37e-8963207c7b86
  secretObjects:
    - data:
        - key: api-bearer-token # data field to populate
          objectName: k8s-secrets-publiccode-crawler-api-bearer-token
        - key: github-token
          objectName: k8s-secrets-publiccode-crawler-github-token
      secretName: publiccode-crawler-with-api-azure-kv # name of the Kubernetes Secret object
      type: Opaque
