---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: default-custom
provisioner: disk.csi.azure.com
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  storageaccounttype: StandardSSD_LRS
  kind: Managed
volumeBindingMode: WaitForFirstConsumer
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: managed-premium-custom
provisioner: disk.csi.azure.com
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  storageaccounttype: Premium_LRS
  kind: Managed
volumeBindingMode: WaitForFirstConsumer
