---
configuration:
  backupStorageLocation:
    - name: default
      provider: azure
      bucket: devita-prod-sc-backups
      config:
        resourceGroup: devita-prod-rg
        storageAccount: devitaprodsabackups
        subscriptionId: d30b533f-c88b-45ec-867e-8e321aa0b03f
  volumeSnapshotLocation:
    - name: default
      provider: azure
      bucket: devita-prod-sc-backups
      config:
        resourceGroup: devita-prod-rg
        subscriptionId: d30b533f-c88b-45ec-867e-8e321aa0b03f
  extraEnvVars:
    AZURE_CREDENTIALS_FILE: /secrets-store/cloud

initContainers:
  - name: velero-plugin-for-microsoft-azure
    image: velero/velero-plugin-for-microsoft-azure:v1.7.1
    volumeMounts:
      - mountPath: /target
        name: plugins

credentials:
  useSecret: false

extraObjects:
  - apiVersion: secrets-store.csi.x-k8s.io/v1
    kind: SecretProviderClass
    metadata:
      name: velero
    spec:
      provider: azure
      parameters:
        keyvaultName: devita-prod-kv
        useVMManagedIdentity: "true"
        userAssignedIdentityID: d7174ca3-5901-47ce-a1f6-32ec772f0de5
        objects: |
          array:
            - |
              objectName: k8s-secrets-velero-03
              objectType: secret
              objectAlias: cloud
        tenantId: f7f7d6c7-92de-488e-b37e-8963207c7b86

extraVolumes:
  - name: secrets-store
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: velero

extraVolumeMounts:
  - mountPath: /secrets-store
    name: secrets-store
