---

apiVersion: spv.no/v1alpha1

kind: AzureKeyVaultSecret
metadata:
  # Name of the secret to reference from env injector
  name: velero-secrets
  namespace: backups
spec:
  vault:
    # Name of the Azure Keyvault
    name: devita-prod-kv
    object:
      # Name of the secret to retrieve from the Azure Keyvault
      name: k8s-secrets-velero
      type: multi-key-value-secret
      contentType: application/x-json
  output:
    secret:
      # Name of the secret in Kubernetes
      name: velero-secrets
