{{- if not .Values.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "publiccode-issueopener.fullname" . }}
  labels:
    {{- include "publiccode-issueopener.labels" . | nindent 4 }}
type: Opaque
data:
  botGithubToken: {{ .Values.secrets.botGithubToken | b64enc }}
{{- end }}
